const tools = [
  { id: 'age-calculator', label: 'Age Calculator', iconName: 'Calendar' },
  { id: 'ascii-converter', label: 'Ascii Converter', iconName: 'Hash' },
  { id: 'aspect-ratio', label: 'Aspect Ratio', iconName: 'Maximize' },
  { id: 'bmi-calculator', label: 'Bmi Calculator', iconName: 'Activity' },
  { id: 'box-shadow', label: 'Box Shadow', iconName: 'Layers' },
  { id: 'chmod-calculator', iconName: 'FileLock' },
  { id: 'cipher-tools', iconName: 'Lock' },
  { id: 'code-editor', iconName: 'FileCode' },
  { id: 'credit-card-validator', iconName: 'CreditCard' },
  { id: 'cron-generator', iconName: 'AlarmClock' },
  { id: 'crontab-generator', iconName: 'Table' },
  { id: 'css-clip-path', iconName: 'Scissors' },
  { id: 'css-cursor', iconName: 'MousePointer' },
  { id: 'css-minifier', iconName: 'Minimize' },
  { id: 'css-triangle', iconName: 'Triangle' },
  { id: 'curl-converter', iconName: 'Terminal' },
  { id: 'date-diff', iconName: 'CalendarDays' },
  { id: 'deep-link-tester', iconName: 'Link2' },
  { id: 'device-info', iconName: 'Smartphone' },
  { id: 'discount-calculator', iconName: 'Tag' },
  { id: 'dns-lookup', iconName: 'SearchCode' },
  { id: 'email-validator', iconName: 'Mail' },
  { id: 'favicon-generator', iconName: 'Image' },
  { id: 'fuel-calculator', iconName: 'Fuel' },
  { id: 'gradient-generator', iconName: 'Palette' },
  { id: 'grid-generator', iconName: 'LayoutGrid' },
  { id: 'hmac-generator', iconName: 'Key' },
  { id: 'htpasswd-generator', iconName: 'UserLock' },
  { id: 'http-status', iconName: 'Activity' },
  { id: 'iban-validator', iconName: 'Landmark' },
  { id: 'image-base64', iconName: 'ImageIcon' },
  { id: 'image-compressor', iconName: 'Shrink' },
  { id: 'image-converter', iconName: 'RefreshCw' },
  { id: 'interest-calculator', iconName: 'Coins' },
  { id: 'json-converter', iconName: 'FileType' },
  { id: 'json-diff', iconName: 'FileDiff' },
  { id: 'keycode-info', iconName: 'Keyboard' },
  { id: 'keyword-density', iconName: 'Type' },
  { id: 'list-sorter', iconName: 'SortAsc' },
  { id: 'loan-calculator', iconName: 'PiggyBank' },
  { id: 'mac-generator', iconName: 'Cpu' },
  { id: 'margin-calculator', iconName: 'SquareStack' },
  { id: 'markdown-editor', iconName: 'Edit' },
  { id: 'markdown-table', iconName: 'Sheet' },
  { id: 'meta-generator', iconName: 'Tags' },
  { id: 'meta-tags', iconName: 'Code2' },
  { id: 'mock-data-generator', iconName: 'Database' },
  { id: 'my-ip', iconName: 'Globe' },
  { id: 'og-generator', iconName: 'Share2' },
  { id: 'password-manager', iconName: 'Vault' },
  { id: 'password-strength', iconName: 'ShieldCheck' },
  { id: 'paypal-link', iconName: 'DollarSign' },
  { id: 'percentage-calculator', iconName: 'Calculator' },
  { id: 'pomodoro-timer', iconName: 'Timer' },
  { id: 'pretty-print-url', iconName: 'Sparkles' },
  { id: 'prime-factors', iconName: 'Divide' },
  { id: 'qr-generator', iconName: 'QrCode' },
  { id: 'random-generator', iconName: 'Dices' },
  { id: 'robots-generator', iconName: 'Bot' },
  { id: 'roi-calculator', iconName: 'TrendingUp' },
  { id: 'roman-numerals', iconName: 'Columns' },
  { id: 'screen-recorder', iconName: 'Video' },
  { id: 'signature-generator', iconName: 'PenTool' },
  { id: 'speech-to-text', iconName: 'Mic' },
  { id: 'sql-formatter', iconName: 'FileJson' },
  { id: 'sql-to-json', iconName: 'ArrowLeftRight' },
  { id: 'stopwatch', iconName: 'Stopwatch' },
  { id: 'subnet-calculator', iconName: 'Network' },
  { id: 'svg-to-png', iconName: 'ImagePlus' },
  { id: 'text-diff', iconName: 'Diff' },
  { id: 'text-to-speech', iconName: 'Volume2' },
  { id: 'text-tools', iconName: 'Wand2' },
  { id: 'timezone-converter', iconName: 'Watch' },
  { id: 'token-generator', iconName: 'Ticket' },
  { id: 'twitter-card', iconName: 'Twitter' },
  { id: 'unit-converter', iconName: 'Ruler' },
  { id: 'url-parser', iconName: 'Link' },
  { id: 'utm-builder', iconName: 'Compass' },
  { id: 'vat-calculator', iconName: 'FileSearch' },
  { id: 'vibration-tester', iconName: 'SmartphoneNfc' },
  { id: 'visual-database-designer', iconName: 'Box' },
  { id: 'week-number', iconName: 'CalendarRange' },
  { id: 'whatsapp-link', iconName: 'MessageCircle' },
  { id: 'yt-thumbnail', iconName: 'Youtube' },
];

const names = tools.map(t => t.iconName);
const duplicates = names.filter((name, index) => names.indexOf(name) !== index);
console.log('Duplicates:', duplicates);
