// External tools configuration for the Chrome Extension
// Version: 1.0.2-pnpm-fix
export const EXTERNAL_TOOLS = [
    { id: 'age-calculator', label: 'Age Calculator', iconName: 'Calendar', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/age-calculator' },
    { id: 'ascii-converter', label: 'Ascii Converter', iconName: 'Binary', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/ascii-converter' },
    { id: 'aspect-ratio', label: 'Aspect Ratio', iconName: 'Maximize', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/aspect-ratio' },
    { id: 'bmi-calculator', label: 'Bmi Calculator', iconName: 'Scale', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/bmi-calculator' },
    { id: 'box-shadow', label: 'Box Shadow', iconName: 'Layers', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/box-shadow' },
    { id: 'chmod-calculator', label: 'Chmod Calculator', iconName: 'FileLock', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/chmod-calculator' },
    { id: 'cipher-tools', label: 'Cipher Tools', iconName: 'ShieldAlert', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/cipher-tools' },
    { id: 'code-editor', label: 'Code Editor', iconName: 'FileCode', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/code-editor' },
    { id: 'credit-card-validator', label: 'Credit Card Validator', iconName: 'CreditCard', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/credit-card-validator' },
    { id: 'cron-generator', label: 'Cron Generator', iconName: 'AlarmClock', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/cron-generator' },
    { id: 'crontab-generator', label: 'Crontab Generator', iconName: 'Table', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/crontab-generator' },
    { id: 'css-clip-path', label: 'Css Clip Path', iconName: 'Scissors', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/css-clip-path' },
    { id: 'css-cursor', label: 'Css Cursor', iconName: 'MousePointer2', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/css-cursor' },
    { id: 'css-minifier', label: 'Css Minifier', iconName: 'Minimize2', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/css-minifier' },
    { id: 'css-triangle', label: 'Css Triangle', iconName: 'Triangle', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/css-triangle' },
    { id: 'curl-converter', label: 'Curl Converter', iconName: 'Terminal', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/curl-converter' },
    { id: 'date-diff', label: 'Date Diff', iconName: 'CalendarDays', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/date-diff' },
    { id: 'deep-link-tester', label: 'Deep Link Tester', iconName: 'Link2', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/deep-link-tester' },
    { id: 'device-info', label: 'Device Info', iconName: 'Smartphone', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/device-info' },
    { id: 'discount-calculator', label: 'Discount Calculator', iconName: 'Tag', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/discount-calculator' },
    { id: 'dns-lookup', label: 'Dns Lookup', iconName: 'SearchCode', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/dns-lookup' },
    { id: 'email-validator', label: 'Email Validator', iconName: 'Mail', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/email-validator' },
    { id: 'favicon-generator', label: 'Favicon Generator', iconName: 'Image', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/favicon-generator' },
    { id: 'fuel-calculator', label: 'Fuel Calculator', iconName: 'Fuel', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/fuel-calculator' },
    { id: 'gradient-generator', label: 'Gradient Generator', iconName: 'Palette', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/gradient-generator' },
    { id: 'grid-generator', label: 'Grid Generator', iconName: 'LayoutGrid', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/grid-generator' },
    { id: 'hmac-generator', label: 'Hmac Generator', iconName: 'Key', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/hmac-generator' },
    { id: 'htpasswd-generator', label: 'Htpasswd Generator', iconName: 'UserLock', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/htpasswd-generator' },
    { id: 'http-status', label: 'Http Status', iconName: 'Activity', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/http-status' },
    { id: 'iban-validator', label: 'Iban Validator', iconName: 'Banknote', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/iban-validator' },
    { id: 'image-base64', label: 'Image Base64', iconName: 'ImageIcon', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/image-base64' },
    { id: 'image-compressor', label: 'Image Compressor', iconName: 'Shrink', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/image-compressor' },
    { id: 'image-converter', label: 'RefreshCw', iconName: 'RefreshCw', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/image-converter' },
    { id: 'interest-calculator', label: 'Interest Calculator', iconName: 'Coins', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/interest-calculator' },
    { id: 'json-converter', label: 'Json Converter', iconName: 'FileType', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/json-converter' },
    { id: 'json-diff', label: 'Json Diff', iconName: 'FileDiff', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/json-diff' },
    { id: 'keycode-info', label: 'Keycode Info', iconName: 'Keyboard', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/keycode-info' },
    { id: 'keyword-density', label: 'Keyword Density', iconName: 'Search', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/keyword-density' },
    { id: 'list-sorter', label: 'List Sorter', iconName: 'ArrowDownAZ', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/list-sorter' },
    { id: 'loan-calculator', label: 'Loan Calculator', iconName: 'Landmark', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/loan-calculator' },
    { id: 'mac-generator', label: 'Mac Generator', iconName: 'Cpu', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/mac-generator' },
    { id: 'margin-calculator', label: 'Margin Calculator', iconName: 'SquareStack', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/margin-calculator' },
    { id: 'markdown-editor', label: 'Markdown Editor', iconName: 'Edit3', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/markdown-editor' },
    { id: 'markdown-table', label: 'Markdown Table', iconName: 'Sheet', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/markdown-table' },
    { id: 'meta-generator', label: 'Meta Generator', iconName: 'Tags', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/meta-generator' },
    { id: 'meta-tags', label: 'Meta Tags', iconName: 'Code2', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/meta-tags' },
    { id: 'mock-data-generator', label: 'Mock Data Generator', iconName: 'Database', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/mock-data-generator' },
    { id: 'my-ip', label: 'My Ip', iconName: 'MapPin', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/my-ip' },
    { id: 'og-generator', label: 'Og Generator', iconName: 'Share2', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/og-generator' },
    { id: 'password-manager', label: 'Password Manager', iconName: 'Vault', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/password-manager' },
    { id: 'password-strength', label: 'Password Strength', iconName: 'ShieldCheck', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/password-strength' },
    { id: 'paypal-link', label: 'Paypal Link', iconName: 'DollarSign', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/paypal-link' },
    { id: 'percentage-calculator', label: 'Percentage Calculator', iconName: 'Calculator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/percentage-calculator' },
    { id: 'pomodoro-timer', label: 'Pomodoro Timer', iconName: 'Timer', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/pomodoro-timer' },
    { id: 'pretty-print-url', label: 'Pretty Print Url', iconName: 'Wand2', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/pretty-print-url' },
    { id: 'prime-factors', label: 'Prime Factors', iconName: 'Divide', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/prime-factors' },
    { id: 'qr-generator', label: 'Qr Generator', iconName: 'QrCode', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/qr-generator' },
    { id: 'random-generator', label: 'Random Generator', iconName: 'Dices', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/random-generator' },
    { id: 'robots-generator', label: 'Robots Generator', iconName: 'Bot', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/robots-generator' },
    { id: 'roi-calculator', label: 'Roi Calculator', iconName: 'TrendingUp', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/roi-calculator' },
    { id: 'roman-numerals', label: 'Roman Numerals', iconName: 'Columns', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/roman-numerals' },
    { id: 'screen-recorder', label: 'Screen Recorder', iconName: 'Video', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/screen-recorder' },
    { id: 'signature-generator', label: 'Signature Generator', iconName: 'PenTool', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/signature-generator' },
    { id: 'speech-to-text', label: 'Speech To Text', iconName: 'Mic', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/speech-to-text' },
    { id: 'sql-formatter', label: 'Sql Formatter', iconName: 'FileText', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/sql-formatter' },
    { id: 'sql-to-json', label: 'Sql To Json', iconName: 'ArrowLeftRight', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/sql-to-json' },
    { id: 'stopwatch', label: 'Stopwatch', iconName: 'Stopwatch', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/stopwatch' },
    { id: 'subnet-calculator', label: 'Subnet Calculator', iconName: 'Network', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/subnet-calculator' },
    { id: 'svg-to-png', label: 'Svg To Png', iconName: 'ImagePlus', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/svg-to-png' },
    { id: 'text-diff', label: 'Text Diff', iconName: 'Diff', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/text-diff' },
    { id: 'text-to-speech', label: 'Text To Speech', iconName: 'Volume2', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/text-to-speech' },
    { id: 'text-tools', label: 'Text Tools', iconName: 'Wand', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/text-tools' },
    { id: 'timezone-converter', label: 'Timezone Converter', iconName: 'Watch', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/timezone-converter' },
    { id: 'token-generator', label: 'Token Generator', iconName: 'Ticket', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/token-generator' },
    { id: 'twitter-card', label: 'Twitter Card', iconName: 'Twitter', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/twitter-card' },
    { id: 'unit-converter', label: 'Unit Converter', iconName: 'Ruler', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/unit-converter' },
    { id: 'url-parser', label: 'Url Parser', iconName: 'Link', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/url-parser' },
    { id: 'utm-builder', label: 'Utm Builder', iconName: 'Compass', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/utm-builder' },
    { id: 'vat-calculator', label: 'Vat Calculator', iconName: 'FileSearch', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/vat-calculator' },
    { id: 'vibration-tester', label: 'Vibration Tester', iconName: 'SmartphoneNfc', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/vibration-tester' },
    { id: 'visual-database-designer', label: 'Visual Database Designer', iconName: 'Box', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/visual-database-designer' },
    { id: 'week-number', label: 'Week Number', iconName: 'CalendarRange', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/week-number' },
    { id: 'whatsapp-link', label: 'Whatsapp Link', iconName: 'MessageCircle', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/whatsapp-link' },
    { id: 'yt-thumbnail', label: 'Yt Thumbnail', iconName: 'PlayCircle', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/yt-thumbnail' },
];
