export const EXTERNAL_TOOLS = [
    { id: 'age-calculator', label: 'Age Calculator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/age-calculator' },
    { id: 'ascii-converter', label: 'Ascii Converter', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/ascii-converter' },
    { id: 'aspect-ratio', label: 'Aspect Ratio', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/aspect-ratio' },
    { id: 'bmi-calculator', label: 'Bmi Calculator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/bmi-calculator' },
    { id: 'box-shadow', label: 'Box Shadow', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/box-shadow' },
    { id: 'chmod-calculator', label: 'Chmod Calculator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/chmod-calculator' },
    { id: 'cipher-tools', label: 'Cipher Tools', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/cipher-tools' },
    { id: 'code-editor', label: 'Code Editor', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/code-editor' },
    { id: 'credit-card-validator', label: 'Credit Card Validator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/credit-card-validator' },
    { id: 'cron-generator', label: 'Cron Generator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/cron-generator' },
    { id: 'crontab-generator', label: 'Crontab Generator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/crontab-generator' },
    { id: 'css-clip-path', label: 'Css Clip Path', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/css-clip-path' },
    { id: 'css-cursor', label: 'Css Cursor', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/css-cursor' },
    { id: 'css-minifier', label: 'Css Minifier', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/css-minifier' },
    { id: 'css-triangle', label: 'Css Triangle', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/css-triangle' },
    { id: 'curl-converter', label: 'Curl Converter', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/curl-converter' },
    { id: 'date-diff', label: 'Date Diff', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/date-diff' },
    { id: 'deep-link-tester', label: 'Deep Link Tester', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/deep-link-tester' },
    { id: 'device-info', label: 'Device Info', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/device-info' },
    { id: 'discount-calculator', label: 'Discount Calculator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/discount-calculator' },
    { id: 'dns-lookup', label: 'Dns Lookup', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/dns-lookup' },
    { id: 'email-validator', label: 'Email Validator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/email-validator' },
    { id: 'favicon-generator', label: 'Favicon Generator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/favicon-generator' },
    { id: 'fuel-calculator', label: 'Fuel Calculator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/fuel-calculator' },
    { id: 'gradient-generator', label: 'Gradient Generator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/gradient-generator' },
    { id: 'grid-generator', label: 'Grid Generator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/grid-generator' },
    { id: 'hmac-generator', label: 'Hmac Generator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/hmac-generator' },
    { id: 'htpasswd-generator', label: 'Htpasswd Generator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/htpasswd-generator' },
    { id: 'http-status', label: 'Http Status', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/http-status' },
    { id: 'iban-validator', label: 'Iban Validator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/iban-validator' },
    { id: 'image-base64', label: 'Image Base64', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/image-base64' },
    { id: 'image-compressor', label: 'Image Compressor', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/image-compressor' },
    { id: 'image-converter', label: 'Image Converter', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/image-converter' },
    { id: 'interest-calculator', label: 'Interest Calculator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/interest-calculator' },
    { id: 'json-converter', label: 'Json Converter', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/json-converter' },
    { id: 'json-diff', label: 'Json Diff', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/json-diff' },
    { id: 'keycode-info', label: 'Keycode Info', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/keycode-info' },
    { id: 'keyword-density', label: 'Keyword Density', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/keyword-density' },
    { id: 'list-sorter', label: 'List Sorter', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/list-sorter' },
    { id: 'loan-calculator', label: 'Loan Calculator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/loan-calculator' },
    { id: 'mac-generator', label: 'Mac Generator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/mac-generator' },
    { id: 'margin-calculator', label: 'Margin Calculator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/margin-calculator' },
    { id: 'markdown-editor', label: 'Markdown Editor', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/markdown-editor' },
    { id: 'markdown-table', label: 'Markdown Table', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/markdown-table' },
    { id: 'meta-generator', label: 'Meta Generator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/meta-generator' },
    { id: 'meta-tags', label: 'Meta Tags', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/meta-tags' },
    { id: 'mock-data-generator', label: 'Mock Data Generator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/mock-data-generator' },
    { id: 'my-ip', label: 'My Ip', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/my-ip' },
    { id: 'og-generator', label: 'Og Generator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/og-generator' },
    { id: 'password-manager', label: 'Password Manager', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/password-manager' },
    { id: 'password-strength', label: 'Password Strength', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/password-strength' },
    { id: 'paypal-link', label: 'Paypal Link', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/paypal-link' },
    { id: 'percentage-calculator', label: 'Percentage Calculator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/percentage-calculator' },
    { id: 'pomodoro-timer', label: 'Pomodoro Timer', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/pomodoro-timer' },
    { id: 'pretty-print-url', label: 'Pretty Print Url', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/pretty-print-url' },
    { id: 'prime-factors', label: 'Prime Factors', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/prime-factors' },
    { id: 'qr-generator', label: 'Qr Generator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/qr-generator' },
    { id: 'random-generator', label: 'Random Generator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/random-generator' },
    { id: 'robots-generator', label: 'Robots Generator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/robots-generator' },
    { id: 'roi-calculator', label: 'Roi Calculator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/roi-calculator' },
    { id: 'roman-numerals', label: 'Roman Numerals', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/roman-numerals' },
    { id: 'screen-recorder', label: 'Screen Recorder', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/screen-recorder' },
    { id: 'signature-generator', label: 'Signature Generator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/signature-generator' },
    { id: 'speech-to-text', label: 'Speech To Text', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/speech-to-text' },
    { id: 'sql-formatter', label: 'Sql Formatter', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/sql-formatter' },
    { id: 'sql-to-json', label: 'Sql To Json', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/sql-to-json' },
    { id: 'stopwatch', label: 'Stopwatch', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/stopwatch' },
    { id: 'subnet-calculator', label: 'Subnet Calculator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/subnet-calculator' },
    { id: 'svg-to-png', label: 'Svg To Png', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/svg-to-png' },
    { id: 'text-diff', label: 'Text Diff', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/text-diff' },
    { id: 'text-to-speech', label: 'Text To Speech', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/text-to-speech' },
    { id: 'text-tools', label: 'Text Tools', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/text-tools' },
    { id: 'timezone-converter', label: 'Timezone Converter', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/timezone-converter' },
    { id: 'token-generator', label: 'Token Generator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/token-generator' },
    { id: 'twitter-card', label: 'Twitter Card', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/twitter-card' },
    { id: 'unit-converter', label: 'Unit Converter', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/unit-converter' },
    { id: 'url-parser', label: 'Url Parser', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/url-parser' },
    { id: 'utm-builder', label: 'Utm Builder', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/utm-builder' },
    { id: 'vat-calculator', label: 'Vat Calculator', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/vat-calculator' },
    { id: 'vibration-tester', label: 'Vibration Tester', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/vibration-tester' },
    { id: 'visual-database-designer', label: 'Visual Database Designer', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/visual-database-designer' },
    { id: 'week-number', label: 'Week Number', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/week-number' },
    { id: 'whatsapp-link', label: 'Whatsapp Link', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/whatsapp-link' },
    { id: 'yt-thumbnail', label: 'Yt Thumbnail', isExternal: true, externalUrl: 'https://dailydev.tools/en/tools/yt-thumbnail' },
];
