name: Publish VS Code Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/vscode-extension

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
        
    - name: Install Dependencies
      run: pnpm install --no-frozen-lockfile
      working-directory: .

    - name: Compile
      run: pnpm run compile

    - name: Publish to VS Code Marketplace
      run: npx vsce publish -p ${{ secrets.VSCE_PAT }}
